travis:
  secure:
    BINSTAR_TOKEN: NSeHZZ1kSx51uf75psUNQYP8ZTlZT5udeZjwPI63sWAyhln+mu/6A1csXRIoQNRV3YYp9a0vKSa6AOxYyAe8gEcosFRrL3dpdaXIV+sfVOSEmD8xRAi3Am/Vm4hmbrbZvmfRb7isvwM0qLgQbDom6JzJejBCUFSPGZBti/6cIIAqBQzqNbvgeIpUc+5HgrmZ3Hst2EKuPEs9XyFU8TOOWiCj5sxvi4FvDCyhNfBSmr4Dma2UN2/EEN0cpl93eiI3QB+VMrdb7k1QvW0LwwqaqpNdeK0S0AiVIt+ebjxLMfVwxGvfQ6r5PvRUvrBNEK2mhUXOSDC0YjBWTTQk2IprnIr35RxtHXzpNqBvpPuWbeR6NhAe/lrDs4ttBuhw43C0LLrygNCWkJSU9JKXeKh7ch4Pya/GVFGN58nlVF/STdmO/XvfyPfI1oq0d4xpPe9aCXlnNbrEiHd8Z8cAHEKtKfi98vT0cX8Fo4R5B8V8socfY56Mtrvffi7ZvVAfo1hDQzkv0hvYkHjibD+PmU8HTAHgHMkzTdO/S9djrebyvGujDjuoH0nGsNtp9lIFmkYm/Jk8ApCsjRPfXwDMZ2PCqBBwgiTz7JVYd8NqtiLJsh8wOMW6yrKNEG0i3Ia7aI0uVunGV6KLLPmh2Yi+BdvySv3Lwoj1QUXGBHsTWE5U3mA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
