travis:
  secure:
    BINSTAR_TOKEN: bS4I4yziL0qR/Fc13XHViX3dXFDV+XnkBOL1bkoPuniPJYdPU5ZSwPvgHeTQi1NvUxLvQakgKEoO2LbUbbev2wGAa74SRHxxxXLNKhVfi0JudFB41eBCb20Yx3cWLvwaRFT4XUTkxS3lWNUIhz07aypG2aBNQ2sPN9yn4jn+sKR5wzw9JdPyb2RmDZjEchuP1UbiGnNS/LIXAop30cDv/3QhJSQhIgjPcwhNDZsUmyfz2yxDYbCzDEav5ljK2JZvV2Fmg8bdKpxMV1ESVCaDUShBNDX459sfPjCCYXnyIGPuFjOkYV3bmfX75XF0cfJ2R020ZfPTjjnNpyjSe7BFj6WOOW541XmOfxxUh/sQ7SIwzzzlO9uA8Q58OB8hNhlec2rQqatgjgOpfr1wf4f8KuyCrXZdlAiNXCjnOxLe6NMJGitblXBZADOZQat/2LP7Rk7g1Q4WVI5P1sJP8Hm7u0lP42kWhn8e+4+qgHB8x9ly2/1OJFNSiaSrYV3LjYM1npB99u1osWPLsh9ZrU0Wggp3rhFpuuZ9FrEM+Z1hUiuTOdLejlUx1J6sz1nkzRj20y3WTpuLd9lkOqDu/Qc0fPZucbNc7qrpf1wYb2SHwzMcYKQZrSvZwErpyM7GhCEGYg2M9r1dgyzWfzN6NSkEgHv+8meXeKm9dFFWuthVovc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
